version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=production
      - PORT=3004
      # Add your environment variables here or use env_file
      # - JWT_SECRET=${JWT_SECRET}
      # - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      # - FIREBASE_API_KEY=${FIREBASE_API_KEY}
    volumes:
      - app_data:/app/server/data
      - app_uploads:/app/server/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3004/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  app_data:
  app_uploads:
